---
title: "Experience"
description: |
  Learn more about Arielle's past experience in journalism and communication strategy.
author:
  - name: Arielle Ostry 
    url: https://arielleostry.netlify.app/
    affiliation: The George Washington University
    affiliation_url: https://www.gwu.edu/
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Arielle Ostry is a graduating senior at The George Washington University looking for work opportunities where she can combine her passion for storytelling with the knowledge and technical skills she has developed while studying at GW's School of Media and Public Affairs and Corcoran School of the Arts and Design.

**Education**

**The George Washington University**, Bachelor of the Arts in Journalism & Mass Communication and Dance *(May 2021)*

**Work Experience**

Assistant Editor at [NYOTA Magazine](http://nyotamagazine.com/)

(Oct 2019 - Present)

-   *Collaborated with the Chief Editor of NYOTA Magazine to develop a cohesive and consistent style for the quarterly publication.*

-   *Edited transcribed interview pieces as well as articles featured in the culture, music, and art sections of the magazine, checking for grammar and spelling typos.*

-   *Pitched story and marketing ideas to the editorial team for future issues.*

Research and Communications Assistant at [Restore America's Estuaries](https://estuaries.org/)

(Aug 2020 - Dec 2020)

-   *Pitched and wrote blog posts for website on estuaries and community organizing.*

-   *Curated social media content to inform and educate public during National Estuaries Week.*

-   *Developed video content for website and social media platforms to engage RAE's audience.*

-   *Assisted CEO in legislative research and messaging for Congressional outreach.*

Writer for [danceviewtimes](https://www.danceviewtimes.com/)

(Jan 2018 - Aug 2020)

-   *Wrote reviews of dance performances at the Kennedy Center and Dance Place for an online dance publication.*

-   *Communicated with DC arts venues concerning information on performances and ticket requests.*

-   *Conducted research on dance companies and performances in order to construct accurate and insightful content.*

Communications Assistant at [The Corcoran School of the Arts and Design](https://corcoran.gwu.edu/)

(May 2018 - Dec 2019)

-   *Wrote content for marketing materials including postcards, brochures, and email blasts to improve the visibility of degree programs and initiatives.*

-   *Maintained Corcoran School's social media accounts to advertise events and promote student engagement.*

-   *Created blog posts on Corcoran website using GW Drupal to highlight student and faculty success, as well as provide updates on Corcoran-related news.*

-   *Replied to emails from public to answer inquiries about the Corcoran school and exhibitions.*

Editorial Communications Intern at [The John F. Kennedy Center for the Performing Arts](https://www.kennedy-center.org/)

(Jan 2019 - May 2019)

-   *Created copy for radio, online ads, print brochures and postcards to market Kennedy Center programming.*

-   *Designed engaging email campaigns to inform public about Kennedy Center performances and events.*

-   *Made updates on website to maintain the accuracy of event pages and blurbs.*
